version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_USER: trade_engine_admin
      MYSQL_PASSWORD: trade_engine_is_666
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql
    networks:
      - network
volumes:
  data:
networks:
  network:
    driver: bridge